[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
jackpot_smart_contract = "CKaQ1zwbTdYoVjBfWMUiZGzTbf8wHfc2ExTRTM79kj7w"

[programs.localnet]
jackpot_smart_contract = "CKaQ1zwbTdYoVjBfWMUiZGzTbf8wHfc2ExTRTM79kj7w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=7387c4ee-fe6a-43a6-96ea-05e6534aa500"
wallet = "../key/uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
